services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch-dev
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: kibana-dev
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch

  api:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    environment:
      - THUMBNAIL_BASE_URL=http://localhost:3000/thumbnails
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST:-http://elasticsearch:9200}
      - ELASTICSEARCH_API_KEY=${ELASTICSEARCH_API_KEY}
      - VIDEOS_INDEX_NAME=${VIDEOS_INDEX_NAME:-videos}
      - CHAT_LOGS_INDEX_NAME=${CHAT_LOGS_INDEX_NAME:-youtube-chat-logs}
      - CORS_ORIGINS=http://localhost:3000
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    restart: on-failure
    depends_on:
      - elasticsearch

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /mnt/f/Dev/utsulog/thumbnails_webp:/app/thumbnails
    command: npm run dev

  batch:
    build:
      context: ./batch
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /mnt/f/Dev/utsulog/videos:/app/videos # 動画リストNDJSON保存用
      - /mnt/f/Dev/utsulog/chat_logs:/app/chat_logs # チャットログ保存用
      - /mnt/f/Dev/utsulog/thumbnails_webp:/thumbnails # サムネイル保存用
      - /mnt/f/Dev/utsulog/videofiles:/app/videofiles # 動画ファイル一覧
    environment:
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - ELASTICSEARCH_URL=${ELASTICSEARCH_HOST:-http://elasticsearch:9200}
      - ELASTICSEARCH_API_KEY=${ELASTICSEARCH_API_KEY}
      - VIDEOS_INDEX_NAME=${VIDEOS_INDEX_NAME:-videos}
      - CHAT_LOGS_INDEX_NAME=${CHAT_LOGS_INDEX_NAME:-youtube-chat-logs}
      - VIDEOS_NDJSON=videos/videos.ndjson # S3 Bucket用オブジェクト名
      - VIDEOFILES_DIR=/app/videofiles # 動画ファイル保存用
      - LOCAL_CHAT_LOGS_DIR=/app/chat_logs # チャットログ保存用
      - THUMBNAILS_DIR=/thumbnails # サムネイル保存用
      - CHANNEL_ID=UC64MV1Dfq3prs9CccXg09rQ # 氷室うつろさん
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    depends_on:
      - elasticsearch

volumes:
  esdata:
    driver: local
